# .github/actions/setup-python-environment/action.yml
name: 'Setup Python Environment'
description: 'Sets up Python, caches dependencies, and installs packages with uv'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/poetry.lock', '**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies with uv
      shell: bash
      run: |
        pip install --upgrade pip
        pip install uv
        uv pip install --system -e .
