# Generated by Django 5.2.1 on 2025-06-07 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "image_processing",
            "0002_alter_image_id_alter_imagetransformation_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedimage",
            name="identifier",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="processedimage",
            name="transformation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processed_image",
                to="image_processing.imagetransformation",
            ),
        ),
    ]
