# Generated by Django 5.2.1 on 2025-06-07 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_processing", "0003_alter_processedimage_identifier_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ProcessingImage",
        ),
    ]
