# Generated by Django 5.2.1 on 2025-06-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_processing", "0004_rename_image_processingimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transformationbatch",
            name="input_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transformation_batches",
                to="image_processing.processingimage",
            ),
        ),
    ]
