# Generated by Django 5.1.6 on 2025-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
