# Generated by Django 5.2.1 on 2025-06-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_alter_placetag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="suggested_tags",
            field=models.ManyToManyField(
                related_name="suggested_places", to="places.placetag"
            ),
        ),
    ]
