name: Humanify CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-environment

      - name: Run tests
        env:
          SECRET_KEY: "django-insecure-1234"
          DJANGO_SETTINGS_MODULE: "humanify_project.settings.test"
          DJANGO_ALLOWED_HOSTS: "*"
          DJANGO_CORS_ALLOWED_ORIGINS: "*"
          DJANGO_CSRF_TRUSTED_ORIGINS: "*"
        run: |
          export PATH="/home/runner/.uv/bin:$PATH"
          uv run coverage run -m pytest --no-migrations -p no:logging
          uv run coverage report -m --omit="*/tests/*,humanify_project/*,apps/*/models.py,apps/conftest.py" --skip-empty

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-environment

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files
